app_name = "mu_detailed_gl_report"
app_title = "Mu Detailed General Ledger"
app_publisher = "Mubtkir"
app_description = "Detailed General Ledger Report"
app_email = "almubtkir@gmail.com"
app_license = "mit"
